saslauthd/Makefile.am

saslmd5.h is already generated somewhere else so there is no need
to point to it here.

Some fixes for distcheck

---

sasldb/sasldb.h

This reverts commit 1518b84c1a1adb1fce4c28da7bfce6bf69064016.
The patch broke the msvc builds using nmake

Revert "Remove LIBSASL_API to sasldb"

---

saslauthd/lak.c

Example warning from the build on Fedora 26 (Rawhide):
```
gcc -DHAVE_CONFIG_H -DSASLAUTHD_CONF_FILE_DEFAULT=\"/etc/saslauthd.conf\" -I. -I. -I.. -I.  -I./include -I./include -I./../include -I/usr/include/mysql    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -I/usr/include/mysql   -fPIC -pie -Wl,-z,relro -Wl,-z,now -c -o lak.o lak.c
lak.c: In function 'lak_group_member':
lak.c:1420:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
if (dn_bv)
^~
lak.c:1423:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
return rc;
^~~~~~
```
Clone from …

saslauthd: Fix indentation to silent GCC6 warnings [-Wmisleading-indentation]

---

plugins/ntlm.c
plugins/otp.c
saslauthd/lak.c

Missing bits from OpenSSL compatibility:
* copy/paste error in `ntlm.c` (and some whitespace cleanup)
* `saslauthd` should use the new API too
Author: Tomas Mraz

Add OpenSSL 1.1.0 support in saslauthd

---

plugins/gssapi.c

The GSS-SPNEGO mechanism has been designed and introduced by Microsoft for use
by Active Directory clients. It allows to negotiate an underlying
Security Mechanism like Krb5 or NTLMSSP.
However, the implementaion in cyrus-sasl is broken and never correctly
interoperated with Microsoft servers or clients. This patch fixes the
compatibility issue which is caused by incorrectly trying to negotiate
SSF layers explicitly instead of using the flags negotiated by GSSAPI
as required by Microsoft's implementation.
Signed-off-by: Simo Sorce <simo@redhat.com>

Fix the GSS-SPNEGO mechanism

---

m4/sasl2.m4
plugins/gssapi.c

This PR has a couple of fixes for the gssapi.c plugin that lead up to adding support for recovering the SSF number from GSSAPI instead of hardcoding it at 56.
The code is backwards compatible, so if the gssapi/krb5 libraries do not support pulling the SSF number off the code fallbacks to the old '56' value.
Note that there are both compile and runtime fallbacks so adding this code should be fully safe.
I've tested it with an LDAP server and verifying the correct SSF ('256' as the enctype used was AES-256) is now returned correctly.

Allow cyrus sasl to get the ssf from gssapi

---

lib/checkpw.c
plugins/gssapi.c

select(2) returns the total number of ready descriptors in all the sets which can be more than 1, this fixes courier-authdaemond sasl authentication on, at least, OpenBSD.

Fix authdaemond authentication on OpenBSD

---

saslauthd/lak.c

Resolve the syntax error introduced by #428 (this change makes it build for me).
The bogus characters are not part of the original patch on launchpad [1].
[1] https://bugs.launchpad.net/ubuntu/+source/cyrus-sasl2/+bug/1188475/comments/1

Remove bogus <> to build the package

---

lib/server.c

Initializing pluglist and plug_entry with NULL pointer To avoid unpredictable errors.
Also:
When libsasl is compiled as static library using VS2013+ it cause a link error ( C4703 ) .
This pull request comes to solve thoses problems.

initialise pluglist and plug_entry with NULL

---

sample/http_digest_client.c

`#include <sasl/sasl.h>` requires that cyrus-sasl headers already be
installed on the system for the build to succeed; `#include <sasl.h>`
will instead pick up the copy present in the source tree.

Make http_digest_client consistent with the other samples

---

include/saslplug.h
sasldb/db_ndbm.c

Officially declare the logging functions as "printf-like" to catch future argument-errors at compile-time.
Provide even more details, when reporting NDBM-operation failures.

When reporting errors, provide even more details.

---

configure.ac

Fix HP's aCC warning about wrong return type for main().
Fix warning about unrecognized option --without-opie.
Thanks dilyanpalauzov for the fixes!

configure.ac (issue #476): Fix configure warnings.

---

include/sasl.h
plugins/gssapi.c

I'm working on moving from an old set of servers running a custom build of Cyrus SASL 2.1.25 to shiny new RHEL 7 servers, and ran into a weird issue with a minimal install.
Without this patch, if there are no installed auxprop plugins GSSAPI authentication makes it through the first 3 steps, then logs "could not find auxprop plugin, was searching for '[all]'" and returns SASL_NOMECH to our application.
a321326ae4d5d79d053926167f76fdad52ec627b made `_sasl_auxprop_lookup()` return SASL_NOMECH when no auxprop plugins are found. 8ab8270447101c5d4262e82b765f8646cf5b989f attempted to fix the GSSAPI plugin, but only modified two of the three calls to `canon_user()` to use SASL_CU_EXTERNALLY_VERIFIED.

Allow GSSAPI to work with no auxprop plugins

---

plugins/gs2.c
plugins/gssapi.c
plugins/ldapdb.c
plugins/scram.c

The GCC format-security warnings are treated as errors now on my machine and therefore prevent building.
Checking the code says, that they are indeed not a arbitrary strings, but static and well-defined in the code, but using format string should not hurt and makes GCC happy. See the commit messages for the warnings/errors details
just a note, that this jumped on me during the testing of `-rc5` build. I didn't see it before.

Avoid passing arbitrary strings as format strings in plugins

---

saslauthd/saslcache.c

It is not allowed by modern C/C++ compilers, for example gcc>=4.

saslcache: fix cast-as-lvalue usage

---

configure.ac

"-R" may be wrong, and proper one should be already detected,
CMU_ADD_LIBPATH_TO macro handle it properly.
resolve #307

configure.ac: fix to set proper rpath flag for sqlite

---

saslauthd/saslauthd.mdoc

This is a patch we have in Fedora for some time (slightly modified). I somehow skipped this one during the previous reviews. I hope it would be useful for upstream too. It might also be useful to add it in some other documentation .
https://src.fedoraproject.org/rpms/cyrus-sasl/blob/master/f/cyrus-sasl-2.1.26-saslauthd-user.patch

Document a way to run saslauthd unprivileged in systemd

---

lib/common.c
lib/dlopen.c
plugins/digestmd5.c
plugins/ldapdb.c
plugins/ntlm.c
saslauthd/saslauthd-main.c
saslauthd/testsaslauthd.c
utils/pluginviewer.c
utils/saslpasswd.c

Recent coverity scan results revealed  some more memory leaks, unchecked return values and uninitialized memory accesses.
This PR is not comprehensive fix of all the errors reported by coverity, but since I went through them, I fixed the most obvious cases.

Several memory leaks/uninitialized memory accesses

---

plugins/gssapi.c

This addresses an issue introduced by commit ff9f9caeb6db6d7513128fff9321f9bd445f58b7, which breaks Heimdal backed GSSAPI authentication.

Fallback gracefully for missing GSS_C_SEC_CONTEXT_SASL_SSF support in Heimdal

---

plugins/gssapi.c

Per @simo5, a failure should be honored/reported if minor status returns non-zero while retrieving the bit strength. See https://github.com/cyrusimap/cyrus-sasl/pull/497 for my previous attempt at this fix.

Set sasl error display string on GSS bit strength lookup failure

---

sample/server.c

Heimdal Kerberos added the gss_get_name_attribute function in 2011, but
the check in server.c was written in 2010.  Update the check to only
include gssapi_ext.h if the underlying Kerberos implementation is not
Heimdal.

Fixes #525 -- Update for modern Heimdal API

---

configure.ac

The --disable-sample option when passed to configure is not honored
correctly. Now this is fixed.

Fixes #524 -- honor disable-sample

---

plugins/Makefile.am
plugins/makeinit.sh
saslauthd/Makefile.am

…with `--enable-ldapdb'
[snip]
| powerpc-wrs-linux-gcc [snip] -I../common
|../../git/saslauthd/lak.c:58:10: fatal error: crypto-compat.h:
No such file or directory
[snip]
The crypto-compat.h locates in git/common/, it should be                                                                                                                           |
`-I../../git/common'
Remove useless `-I$(top_srcdir)/../include' which was incorrectly
added by commit `faae590 cleanup misc INCLUDES for different build paths'
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>

Allow saslauthd to be built outside of source tree and fix parallel build issue

---

lib/dlopen.c

I have no idea why at some point it was changed to .plugin
but autotools defaults to .so and we are actually getting
.so files built.

dlopen: on osx the plugins are built as .so

---

common/crypto-compat.c
common/crypto-compat.h

bn.h was missing. Including engine.h does not work if OpenSSL was built
without it. cyrus-sasl makes no use of it anyway.

openssl: Fix compilation without deprecated APIs

---

pwcheck/pwcheck_getspnam.c

The file
pwcheck/pwcheck_getspnam.c
contains a call to strcmp(), but does not include string.h.
While this will sometimes work due to indirect includes of string.h or lenient compilers, it's not correct and you cannot rely on it. Therefore it's better to explicitly include headers for the functions used.
(I found this while going through the patches in the Gentoo package of cyrus-sasl, and this seemed obvious and simple enough to push upstream.)

Add missing string.h include for strcmp().

---

README.md

The link in the README points to some dead address, update with the currently working one.

Fix link to mailing list archives

---

plugins/digestmd5.c

free_rc4 can be called multiple times on the same context as reported in the mailing list.
This patch adds guards to NULL pointers after free is called.

Prevent double free of RC4 context

---

include/makemd5.c

Silences Coverity
Although the code never passes in types that can cause the buffer
to actualy overflow, Coverity flags it, and the fix is simple.

Fix potential out of bound writes

---

configure.ac
plugins/digestmd5.c

This patch let's us use the openssl provided RC4 via the sanctioned EVP interface.
It would be nice if we could completely drop custom implementations of cryptography, but for our uses it is enough that we do not have to use custom crypto by compiling it out.
I tested this patch via sample-server/sample-client forcing DIGEST-MD5 and minssf of 128, everything works as expected.
Please let me know if this is the right way to go to start replacing open coded cryptographic algorithms with the OpenSSL EVP interface, I would like to move DS and MD5 too eventually.

Use Openssl's EVP implementation of RC4 when available

---

configure.ac
saslauthd/auth_rimap.c

read_response uses memmem, which is not available on e.g. Solaris 10

auth_rimap: provide naive memmem implementation if missing

---

lib/checkpw.c

Since PATH_SASLAUTHD_RUNDIR and "/mux" are both fixed strings at compile time, they can be concatenated and handled as one string.

lib/checkpw.c:saslauthd_verify_password: skip one strcat call

---

m4/sasl2.m4

4b0306dcd76031460246b2dabcb7db766d6b04d8 added a configure check for another GSSAPI function, however it forgot to restore `LIBS` after doing so.
The impact of this is that GSSAPI libs are included in **all** link lines, c.f. [this Debian build log](https://buildd.debian.org/status/fetch.php?pkg=cyrus-sasl2&arch=amd64&ver=2.1.27~rc8-1&stamp=1538479977&raw=0):
```
libtool: link: gcc -shared  -fPIC -DPIC  .libs/auxprop.o .libs/canonusr.o .libs/checkpw.o .libs/client.o .libs/common.o .libs/config.o .libs/external.o .libs/md5.o .libs/saslutil.o .libs/server.o .libs/seterror.o .libs/dlopen.o  -Wl,--whole-archive ../common/.libs/libplugin_common.a -Wl,--no-whole-archive  -L/usr/lib/x86_64-linux-gnu/heimdal -L/usr/x86_64-linux-gnu/lib -L/usr/lib -ldl -lresolv -lgssapi -lkrb5 -lasn1 -lroken …
```

Restore LIBS after checking gss_inquire_sec_context_by_oid

---

docsrc/sasl/reference/manpages/library/sasl_decode64.rst
docsrc/sasl/reference/manpages/library/sasl_encode64.rst

They declare the type of function argument "output" as
const char **
but in the saslutil.h header it is declared as
char *

Fix man pages for sasl_decode64 and sasl_encode64

---

sasldb/db_gdbm.c

`gdbm_close` also sets gdbm_errno since version 1.17.
This leads to a problem in `libsasl` as the `gdbm_close` incovation overlays
the `gdbm_errno` value which is then later used for the error handling.
Downstream bugs:
* Archlinux: https://bugs.archlinux.org/task/59873

db_gdbm: fix gdbm_errno overlay from gdbm_close

---

plugins/gssapi.c

Changes in the pull request #575 introduced a bug which prevented the SASL client from retrieving a credential from the credentials cache, while the intended behavior is that the client looks for the credential in the specified keytab file, then if not found, looks into the credentials cache.  This patch fixes the wrong behavior.

Fix a bug which prevented the client from retrieving a credential from CCACHE.

---

plugins/gssapi.c

Hello, I think the change to call gss_acquire_cred() in the client code, is not correct.
Commit 238380260fe623212c0f21d63e763b7a849540d1 broke GSSAPI kerberos authentication, and commit 74faca7400f414784b5e2e136668e6f4ef0d6b96 "fixed" it by ignoring the error (which in my opinion will always occur, as below).
First, calling gss_acquire_cred() to acquire initiator client credentials and passing 'text->server_name' as client desired_name would never make sense, unless the only use case is when the client and server are the same principal, i think this can never work.
Secondly, gsskrb5_register_acceptor_identity() is for acceptor keytab, it is not for initiator, if it makes any impact then it may be a bug.
Instead, you can just use 'default_client_keytab_name' which is supported on modern …

Revert the change to acquire init credentials

---

saslauthd/lak.c

Setting the ldap_tls_check_peer parameter to no does not take effect. 
logical error, if  conf->tls_check_peer is 0, will not execute ldap_set_option, never set LDAP_OPT_X_TLS_REQUIRE_CERT to 0

Ldap_tls_check_peer takes effect for no

---

.gitignore
.travis.yml
Makefile.am
configure.ac
tests/Makefile.am
tests/runtests.py
tests/t_common.c
tests/t_common.h
tests/t_gssapi_cli.c
tests/t_gssapi_srv.c

This runs in make check so hopefully it will work as CI via travis
First test is for SASL/GSSAPI
Fixes #595

Add basic test infrastructure

---

configure.ac
lib/client.c
lib/common.c
lib/saslint.h
lib/saslutil.c
mac/CommonKClient/mac_kclient3/Headers/Kerberos5/win-mac.h
saslauthd/auth_sasldb.c

Per RFC 1035 the maximum FQDN is 253 chars, and not MAXHOSTNAMELEN which
varies between 64 and 1024 bytes depending on the system used.
Define and use a new variable.
Also fix get_fqhostname() to insure that the name returned is zero
terminated.
Fixes #583

Use proper length for Fully Qualified Domain Names

---

configure.ac

The exit function requires to include stdlib otherwise
this will fail on new versions of MacOS

configure: fix check for dlsym underscore

---

docsrc/sasl/installation.rst

I noticed several typos in the installation section, so this PR fixes them.

docs: fix some typos in installation section

---

lib/common.c

Issue #587 was not solved correct.
_sasl_add_string adds zero terminator to the output string.
This cuts log messages after the first '%s' of the format string.
With the fix the function _sasl_log now logs the complete message.
Signed-off-by: Guido Kiener <guido@kiener-muenchen.de>

Fix _sasl_add_string

---

plugins/scram.c

When server does not support channel binding, but client requires
channel binding with the second message, then the server crashes with
an exception in strcmp(sparams->cbinding->name, ...)

SCRAM Fix: Exception when server does not support channel binding

---

common/Makefile.am

This fixes the build with slibtool (https://git.foss21.org/slibtool) which is an alternative implementation for GNU libtool.
```
rdlibtool  --tag=CC   --mode=link clang  -Wall -W -g -O2 -version-info  -no-undefined  -o libcrypto_compat.la  crypto-compat.lo  -lresolv 
rdlibtool: error: option [--version-info] requires a value 
make[2]: *** [Makefile:481: libcrypto_compat.la] Error 2
make[2]: Leaving directory '/tmp/cyrus-sasl/common'
make[1]: *** [Makefile:677: all-recursive] Error 1
make[1]: Leaving directory '/tmp/cyrus-sasl'
make: *** [Makefile:545: all] Error 2
```
The GNU libtool documentation for `-version-info` says:
> This flag accepts an argument of the form ‘current[:revision[:age]]’. So, passing -version-info 3:12:1 sets current to 3, revision to 12, and age to 1.
>
> If either …

common: Define the missing crypto_compat_version version.

---

lib/saslutil.c

The reason of the PR is memory corruption in get_fqhostname.
name[namelen] = '\0' is effectively out of bounds if namelen is sizeof, which is the case.
The issue introduced in cafd436fdb7bb79554b9564acf8345d21e25604d

respect namelen in get_fqhostname

---

AUTHORS
configure.ac
docsrc/sasl/options.rst
plugins/gssapi.c

This feature enables CyrusSASL to forward/delegate GSSAPI Kerberos cached credentials for authenticating to other services on the server-side, as suggested in Issue #585. It also optionally implements service keytab loading with gss_acquire_creds_from() to enable privilege separation using e.g. GSSProxy on a POSIX server.
The feature is implemented on behalf of Vricon Systems AB

plugins/gssapi: Implement credentials cache for delegation

---

docsrc/sasl/components.rst
docsrc/sasl/quickstart.rst
docsrc/sasl/sysadmin.rst

Files: sysadmin.rst, components.rst, quickstart.rst

Convert obsolete HTML references to rst form.

---

saslauthd/auth_krb5.c
saslauthd/krbtf.c

I went down a bit of a rabbit hole with this one.
7c779a14f48d0efe51378516c82a0d6da3fa43da is a patch that we've had deployed at UMich for ages. It adds support for specifying an explicit server name in saslauthd's configuration, which simplifies deployment in cases where it's difficult for the server to automatically determine which principal it should use. One example is an EC2 instance: the IP resolves to a random Amazon hostname and the instance itself usually thinks it's something like ip-172-31-31-254.us-west-2.compute.internal.
Our patch only touched the MIT implementation, so I thought it would be nice to add the same functionality to the Heimdal code before upstreaming...which turned out to be possible, but significantly changed the Heimdal implementation of `auth_krb5()`...to …

saslauthd: auth_krb5 rewrite

---

configure.ac
lib/Makefile.am
sasldb/Makefile.am

1. Rename `SASL_STATIC_LIBS` to `SASL_STATIC_LIB` to free up `SASL_STATIC_LIBS` for
the list of additional libraries needed by static libsasl due to the plugins
that are included in libsasl only in the static build.
2. Add `LIB_DES` to `SASL_STATIC_LIBS` for the digestmd5 plugin.
3. Add `SASL_DB_LIB` to the list of libraries needed by libsasldb.
The second point fixes linking `utils/dbconverter-2` which fails with:
```
ld: ../lib/.libs/libsasl2.a(digestmd5.o): in function `init_3des':
lib/digestmd5.c:968: undefined reference to `DES_key_sched'
```
The third point fixes linking `sample/client` which fails with:
```
ld: ../lib/.libs/libsasl2.a(db_berkeley.o): in function `berkeleydb_open':
lib/db_berkeley.c:103: undefined reference to `db_create'
```
---
This was broken some time between …

Fix build with --disable-shared --enable-static

---

m4/sasl2.m4
plugins/gssapi.c
tests/runtests.py
tests/t_common.c
tests/t_common.h
tests/t_gssapi_cli.c
tests/t_gssapi_srv.c

In GSS-SPNEGO ssf negotiation is implicit and depends on GSSAPI level Integrity and Confidentiality flags.
In order to interoperate with Windows, which does not allow nested security layers, we need to be able to set ssf to 0 when GSS-SPNEGO is negotiated within an outer TLS channel.
Unfortunately MIT's GSSAPI always forces negotiation of Integrity and Confidentiality regardles of what flags are passed to gss_init_sec_context()
Add code to allow MIT to skip setting those flags on the wire as Windows interprets those as a *request* rather than an offer like MIT does.

Allow GSS-SPNEGO to negotiate a ssf of 0

---

lib/checkpw.c
tests/t_gssapi_srv.c

Until documentation on expected behavior is provided, and
flags are reworked to prevent its misuse on auxprop plugins\
that don't support it. Fixes #374

Fix #374: disable auxprop-hashed

---

m4/sasl2.m4

A cross build fails detecting whether GSSAPI supports SPNEGO.
Others ran into this problem already.
While the OE folks produced a patch, they didn't make it upstreamable. I
think we can do better. The attached proposes using AC_CACHE_CHECK
(which is good practise for any AC_TRY_RUN)
Helmut Grohne provided this patch with the explicit intention to upstream it.
Link: http://lists.openembedded.org/pipermail/openembedded-devel/2013-June/091202.html
Link: https://lists.andrew.cmu.edu/pipermail/cyrus-sasl/2016-October/002906.html
Link: https://bugs.debian.org/928512
Reported-by: Helmut Grohne <helmut@subdivi.de>
Signed-off-by: Bastian Germann <bage@debian.org>

Enable cross builds with SPNEGO detection

---

INSTALL.TXT

It looks like the docs recently moved to the `legacy` folder.
If we should rather point to a different resource, we can do so, too.

Update path to installation instructions

---

saslauthd/auth_sasldb.c

I am doing some development in an ubuntu 20.4 (LTS) (focal) box and had some trouble re-building the package w/o any Debian specific patches. This commit fixes those.
-----
Details:
To build, I use some minimal debian/rules / debian/control files that I have uploaded here: https://github.com/Pfiver/cyrus-sasl/commit/48fb14efcce0e32f3264b057dabb4b2466eb6637
Essentially,
```
configure \
--prefix=/usr \
--build=x86_64-linux-gnu \
\
--enable-static \
--enable-shared \
--enable-alwaystrue \
--enable-cram \
--enable-digest \
--enable-plain \
--enable-anon \
--enable-login \
--enable-ldapdb \
--enable-auth-sasldb \
\
--disable-otp \
--disable-srp \
--disable-srp-setpass \
--disable-krb4 \
--disable-gssapi \
--disable-gss_mutexes \
--disable-sql \
--disable-ntlm \
--disable-passdss \ …
```

fix build error w/ --enable-auth-sasldb

---

plugins/digestmd5.c

The "DIGEST-MD5 common mech free" debug log message is bothering many users.
It is not really helpful, so drop it.
Fixes #386.

plugins/digestmd5: Remove debug log "mech free"

---

plugins/digestmd5.c
plugins/scram.c
saslauthd/lak.c

In OpenSSL 3.0 these algorithms have been moved to the legacy provider
which is not enabled by default. This means allocation can and do fail.
Handle failed allocations by returning an actual error instead of
crashing later with a NULL context.
Also deal with deprecation warnings about HMAC()

OpenSSL 3 fixes

---

lib/Makefile.am

This patch makes sure the non-PIC version of libsasldb.a, which
is created out of non-PIC objects, is not going to overwrite the PIC version,
which is created out of PIC objects. The PIC version is placed in .libs, and
the non-PIC version in the current directory.  This ensures that both non-PIC
and PIC versions are available in the correct locations.

Don't overwrite PIC objects with non-PIC variant

---

lib/dlopen.c

I have a service which loads some components using `dlopen()`.  After loading each component it calls `dlerror()` and throws an exception if there is an error.  This used to work fine (ubuntu focal) but doesn't anymore (ubuntu jammy).
The problem is that one of the components depends on libsasl which in turn uses `dlopen()` and `dlsym()` to load its plugins.  Errors happen during plugin loading which are exposed to my service when it calls `dlerror()`.  My suggestion is to call `dlerror()` in libsasl to clear the error.
Also if anyone knows why my service used to work and now doesn't (it hasn't changed), I'd love to know.

Clear error from dlsym() so that it is not exposed outside libsasl

---

m4/plain.m4
m4/sasl2.m4
plugins/Makefile.am

The problem is that on newer Linux, for example Arch Linux 2022-09, the deprecated library is missing. This causes plugins to fail to load.
It was last needed more than 20 years ago, and was removed in commit
74135b68 by Larry Greenfield, 1999-06-23 00:16:37
latest stuff
Later, `#include <crypt.h>` was also removed in commit
f58e0357 by Larry Greenfield, 2000-02-27 23:46:15
removed superfluous includes, brought in line with new checkpass()

Do not add unneeded `-lcrypt` in `plain`, `login` plugins

---

saslauthd/lak.c

Fixes #274, cleanup of the original patch from John Newbigin
**Changes**:
- handle a few more error cases that were silently ignored in the past
- close the input file as soon as it's not needed anymore (before logging)
**NOTE** there are clearly some caveats leftover here regarding the parameters. In the past some of these default to a value and setting this one explicitly runs into the "else" case now. This needs to be tidied up or considered during code review.

Fixes #274: Improve error handling in configuration parser

---

utils/testsuite.c

In some systems, char is compiled as unsigned char by default, as a result, testsuite always fails in abnormal process.

Use int instead of char for variable c

---

configure.ac

On macOS 11+, clang compiler defaults to `-Wimplicit-function-declaration`.
This causes `configure` to incorrectly think that underscores are needed:
```
configure:15316: checking for underscore before symbols
configure:15332: result: yes
configure:15338: checking whether dlsym adds the underscore for us
configure:15360: gcc -o conftest <...> conftest.c  -ldl >&5
<...>
conftest.c:38:23: error: implicitly declaring library function 'exit'
with type 'void (int) __attribute__((noreturn))'
[-Werror,-Wimplicit-function-declaration]
if(ptr1 && !ptr2) exit(0); } exit(1); }
^
conftest.c:38:23: note: include the header <stdlib.h> or explicitly
provide a declaration for 'exit'
1 warning and 1 error generated.
configure:15360: $? = 1
configure: program exited with status 1
```
This causes plugins to …

fix build on macOS 11+

---

lib/md5.c

"As explained in dffe0b3e86925c95e6f30ec0f2de9fb0c439c7bc, the RSA-MD-licensed file md5.c can be relicensed easily because the third-party code that was licensed under RSA-MD is eliminated by now."
-- Bastian Germann <bage@debian.org> in GitHub issue #769
The commit referenced was part of GitHub PR #767 and was authored by Bastian Germann.
I reviewed the commit history on this file.  I concurred with Bastian's original assessment that the relevant detail was Rob Earhart's code, and Bastian agreed with my analysis in the bug.
The next step was confirming that the MD5 code that Rob Earhart contributed was/is licensed under the same license as the rest of the project.  This is a reasonable assumption, as he was one of the main authors of the original code, and everything else he contributed …

Relicense md5.c

---

plugins/scram.c

This reverts one commit from #653.
The HMAC() function was never deprecated as opposed to HMAC_Init() and other related functions.
The alternative HMAC implementation is unnecessary.

Revert "Add a HMAC wrapper for deprecated function"

---

configure.ac
m4/sasldb.m4

0b104e52fe (Fix 718 - Remove BDB support) has removed a m4 fi and a configure.ac test verb. Recover them.
This should go to 2.1.29!

Correct m4 syntax error

---

sample/client.c
sample/common.c
sample/common.h
sample/server.c

The function name collides with a macro defined by glibc for gcc < 4.3 and clang. Rename to prevent that.
Fixes #657
Replaces #616

sample: Rename dprint function

---

plugins/opaque_impl.c

memcpy() is used in the opaque implementation and needs string.h.

opaque: Add missing include

---

configure.ac

aa0cf8b47a (Delete Kerberos V4 support) removed the SASL_DES_CHK definition and implementation. Remove the configure call.

Remove SASL_DES_CHK call

---

docsrc/sasl/options.rst
plugins/gssapi.c
tests/runtests.py
tests/t_gssapi_cli.c
tests/t_gssapi_srv.c

With the current code, it's impossible for a single service to accept multiple service principals. This prevents a single server from being known by multiple FQDNs (e.g. the host FQDN and an anycast FQDN). The code also makes assumptions about how the service principal name should be constructed. This PR addresses both issues by adding support for 2 new options:
accept_any_principal: do not specify the service principal name
service_principal: specify the desired service principal name instead of generating it
I'd argue that best practice would be to make accept_any_principal the norm and delete a lot of code, but I didn't want to change existing behaviour.
I also added client support for the existing keytab option.

Support multiple service principals in a single GSSAPI service

---

utils/testsuite.c

Running testsuite on Solaris seeing a SEGV for every mech.  Its an indexing issue, looks to be the same issue reported for windows by  #790

testsuite SEGV due to index error in testseclayer()

---

saslauthd/auth_krb5.c

This avoids the unpleasant UX on some services of `uniqname@umich.edu` not working for login when `uniqname@UMICH.EDU` does.
Our initial implementation was to apply this transformation unconditionally, but [Kerberos realms are case-sensitive](https://datatracker.ietf.org/doc/html/rfc4120#section-6.1) (uppercase realms are just a convention) so I made a config flag that defaults off for backwards compatibility.

auth_krb5: add flag to automatically uppercase realms

---

common/Makefile.am
sasldb/Makefile.am

The errornously provided PIC flag "-fPIC" (to AM_CPPFLAGS) is non-portable and not required since the generated libtool script will contain the correct PIC flag for the target platform and compiler.
This fixed #798

Remove redudant and non-portable PIC flag (#798)

---

saslauthd/auth_krb5.c

This avoids unnecessary network calls that attempt to get a useless ticket.
We've been running this in production for a while, in response to an incident where clients attempting to log in to an incorrect but resolvable realm with unreachable KDCs took quite a while to time out and tied up server resources.

auth_krb5: compare realms before fetching credentials

---

saslauthd/saslauthd-main.c

add -f option to disable daemonizing without activating verbose output at the same time
Useful for service supervision schemes like runit, that rely on the supervised process to run in foreground. Coupling foreground + verbose in this case is not really useful. This does not change the behavior of the existing options.

saslauthd: add -f (foreground) option

---

utils/saslpasswd.c

Drop code to delete obsolete (Cyrus SASL 1.x) password records. Closes #264

saslpasswd2: delete obsolete code

---

configure.ac
lib/common.c
m4/ax_pthread.m4
m4/sasl2.m4

Add `--with-threads=<implementation>` configure option that makes `sasl_client_init`/`sasl_server_init` thread safe. Some code is borrowed from OpenLDAP, @hyc can you review this is OK copyright-wise? Some of it (e.g. Windows side of `_sasl_mutex_init`, probably the whole NT infra) is yours.

Init with threads

---

sample/sample-client.c
utils/Makefile.am
utils/pluginviewer.c

Closes #339
Most of the changes mentioned there were already committed in #528 This commit just removes some unused references to PLUGINDIR.

plugindir cleanup

---

plugins/scram.c

Using mechanism SCRAM, a client does not abort authentication when the given iteration counter is lower than 4096.
A hostile server can send a small iteration counter (e.g. 1) and forces the client to send a ClientProof that is calculated with lowest computation time. Thus the hostile server can recover the client's password faster with an offline dictionary or brute-force attack.
This fix compares the iteration counter with the recommended minimum of 4096 and aborts the authentication if the server violates the recommended minimum.

SCRAM: Client does not check low iteration counter #811

---

saslauthd/auth_pam.c
saslauthd/auth_pam.h

Fabian Knittel agreed to changing the license to the standard BSD-2-clause license in the linked GitHub issue.
Fixes: #698

saslauthd: Relicense auth_pam under BSD-2-Clause

---

lib/common.c

In `sasl_done_common`, we free `free_mutex`. However, if `sasl_mutex_init` was never called, `free_mutex` is `NULL`.
This has been fine because user likely won't call `sasl_set_mutex` either if they never initalized sasl, but with #803, we start to supply default pthread implementation for `sasl_mutex_free` and this starts segfaulting when a process calls `sasl_done` without `sasl_{client,server}_init`.
This commit changes it such that we only free `free_mutex` if it's not null. We already have similar checks for other variables to free (e.g. `global_mech_list`)
The segfault can be reproduced with:
```
#include <stdio.h>
#include <sasl/sasl.h>
int main() {
sasl_done();
return 0;
}
```
I confirmed that it does not segfault after this commit (as well as before #803). …

Fix that sasl_done segfaults without init

---

lib/server.c

Calculation of resultlen is wrong. E.g. if server allows only one mechanism SCRAM-SHA-256, the expected string for the mechlist_buf is "SCRAM-SHA-256-PLUS SCRAM-SHA-256" with a required size of 33 bytes and not 32 bytes.
Note that (strlen(mysep) * (s_conn->mech_length - 1) * 2) = 0 when s_conn->mech_length = 1.

Fix heap corruption

---

lib/common.c
lib/saslutil.c
lib/windlopen.c
sample/client.c

Some missing #includes, minor stuff.
Reminder: you must run configure with `--without-saslauthd --without-authdaemond` since there's no Windows IPC support in either of those.

More Win32 build fixes

---

m4/sasl2.m4

When <gssapi/gssapi_krb5.h> stems from Heimdal but build-heimdal/config.h doesn't define HAVE_GSSAPI_GSSAPI_KRB5_H, <gssapi/gssapi_krb5.h> is not included.
The header file is only checked if gsskrb5_register_acceptor_identity is not found.
Move the header check so that it works for both KRB5 and Heimdal.
Link: https://bugs.debian.org/1066214

sasl2.m4: Check for gssapi_krb5.h before testing a resulting value

---

lib/saslutil.c
plugins/otp.c
saslauthd/saslcache.c

In some format strings, it is expected that time_t is the same size as long. long is 32 bit for 32 bit architectures, while time_t might be 64 bit. Extend the format string specifiers to long long, which can hold a time_t regardless of the platform and libc configuration.
Closes: #484

Extend the time_t format specifiers to long long

---

include/sasl.h
plugins/gs2.c
plugins/scram.c
sample/client.c
sample/server.c

Provide a callback function to change the channel binding type of servers (e.g. "tls-server-end-point" instead of "tls-unique") during authentication of secure mechanisms like GS2-KRB5-PLUS or SCRAM-SHA-256-PLUS.
The callback is used by the plugins SCRAM and GS2 when the desired binding type of the client does not match the binding type set with property SASL_CHANNEL_BINDING.
A server can check the requested type of channel binding and overwrite the current channel binding data with the property SASL_CHANNEL_BINDING before the authentication proceeds.
Issue #823
This patch is required to support channel binding for "tls-server-end-point" in cyrus-imapd.
See example: https://github.com/GuidoKiener/cyrus-imapd/commit/5e0af184fe8de71526bd103ecd351d70600ae863
Note that the example is not …

Add callback SASL_CB_SERVER_CHANNEL_BINDING

---

docsrc/sasl/reference/manpages/library/sasl_decode64.rst
docsrc/sasl/reference/manpages/library/sasl_dispose.rst
docsrc/sasl/reference/manpages/library/sasl_encode.rst
docsrc/sasl/reference/manpages/library/sasl_encodev.rst

sasl_encode and sasl_encodev were defined twice. Reduce the definitions to one for each document.
sasl_dispose had the wrong definition (copy/paste error). Replace it.
sasl_decode64 has a typo in unasigned. Correct it.
This is a follow-up on #817

docsrc: Correct rst syntax

---

lib/auxprop.c
lib/canonusr.c
lib/client.c
lib/common.c
lib/saslint.h
lib/server.c
saslauthd/auth_sasldb.c
saslauthd/saslauthd-main.c
saslauthd/saslauthd-main.h

Fedora 42 is going to use gcc 15 which changes some warnings into errors. Address the issues raised.
The issues addressed include:
- The RETURN macro is defined differently in two places. Rename one.
- Both atexit and the sigint and sigterm actions call server_exit(). The function arguments diff. Introduce a new generic signal handler to call server_exit() for sigint and sigterm signals.

Add compatibility for gcc 15
