cyrusimap/cyrus-sasl

sasldb/db_ndbm.c
Just change to same as other backends.
=> clean up ndbm backend for sasldb

plugins/digestmd5.c
Se my mail at cyrus-devel ML:
https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2017-May/004063.html
=> Fix division-by-zero in reauth

doc/options.html, docsrc/sasl/options.rst, m4/sasldb.m4
Some minor cleanup for the new LMDB feature
=> For https://github.com/cyrusimap/cyrus-sasl/issues/403

saslauthd/ipc_unix.c
=> Fixes https://github.com/cyrusimap/cyrus-sasl/issues/445 prevents early

configure.ac, saslauthd/Makefile.am
resolve regression from 0c0f7aa97a79ae2a024cae1eec600d0ce70ffdb4
=> saslauthd: Fix to link with libsasldb conditionally

configure.ac
Reverts cyrusimap/cyrus-sasl#512
=> Revert "configure.ac: fix condition for suppliment snprintf implementation"

common/plugin_common.c
Original name breaks build with mingw
=> Use lower-case versionhelpers.h

saslauthd/Makefile.am
Fixes #519 
Fixes #373 
Fixes #504
=> Fix testsaslauthd.8 manpage and saslauthd manpage installation

plugins/gssapi.c
gss_init_sec_context() with GSS_C_NO_CREDENTIAL ignores a configured keytab by using gsskrb5_register_acceptor_identity().  This patch adds a gss_acquire_cred() call before gss_init_sec_context() to get a credential from the specified KRB5 keytab.
Note that gssapi_server_mech_step() already has the same code path and it works as expected while  the client version does not.  There is a case that a SASL client application uses a keytab.  However, the current code prevents it from working.  This change should have no harmful effect when not using gsskrb5_register_acceptor_identity().
This patch also includes a change to add a gsskrb5_register_acceptor_identity() call in gssapiv2_client_plug_init().   If gssapiv2_server_plug_init() is always called together, this is redundant.
=> Call gss_acquire_cred() before gss_init_sec_context() in gssapi_client_mech_step()

config/sasl.spec, doc/legacy/TODO, doc/legacy/components.html, doc/legacy/index.html, doc/legacy/install.html, doc/legacy/readme.html, doc/legacy/sysadmin.html, docsrc/index.rst, docsrc/sasl/components.rst, docsrc/sasl/faqs/crammd5-digestmd5-scram.rst, docsrc/sasl/faqs/plaintextpasswords.rst, docsrc/sasl/faqs/rfcs.rst, docsrc/sasl/installation.rst, docsrc/sasl/quickstart.rst, docsrc/sasl/sysadmin.rst, plugins/scram.c
Some little changes:
- RFC7677 + RFC7804 in doc
- Better RFCs/Drafts order
- SCRAM-SHA-1 SASL plugin -> SCRAM-SHA-1/SHA-2 SASL plugin
- RFC5929 in doc
=> Some little changes

plugins/gssapi.c, tests/runtests.py, tests/t_common.c, tests/t_common.h, tests/t_gssapi_cli.c, tests/t_gssapi_srv.c
This works and comes with both a positive and a negative test.
Fixes #600
=> Add GSSAPI Channel Binding support

contrib/tclsasl/doc/tclsasl.html, contrib/tclsasl/doc/tclsasl.xml, doc/legacy/components.html, doc/legacy/index.html, doc/legacy/macosx.html, doc/legacy/options.html, doc/legacy/readme.html, doc/legacy/sysadmin.html, docsrc/sasl/components.rst, docsrc/sasl/faqs/rfcs.rst, docsrc/sasl/macosx.rst, docsrc/sasl/options.rst, docsrc/sasl/quickstart.rst, docsrc/sasl/sysadmin.rst, utils/saslpasswd2.8
=> Update of docs

sample/Makefile.am
=> Fixes issue#646 sample build when builddir is not equal to srcdir

saslauthd/auth_rimap.c
=> memmem() - change condition of while statement

tests/runtests.py, tests/t_gssapi_cli.c, tests/t_gssapi_srv.c
Here are some very basic PLAIN sasl mechanism tests.
It's worth renaming the t_gssapi* files to something more general, if there is any interest to this PR.
=> Some basic PLAIN auth tests

.travis.yml
Signed-off-by: Quanah Gibson-Mount <quanah@symas.com>
=> Fix #661 - Fix formatting of travis YML file

Makefile.am, configure.ac
This is just an FYI PR, if someone has difficulty with the 2,1 due to it
=> wip: remove java support from 2.1 tree

docsrc/sasl/release-notes/2.1/index.rst
This is not meant to be exhaustive as so many changes have gone in, but I tried to highlight as much as possible.
=> Release notes for 2.1.28

doc/legacy/sysadmin.html, docsrc/sasl/reference/manpages/library/sasl_getsimple_t.rst, docsrc/sasl/reference/manpages/library/sasl_server_userdb_setpass_t.rst, docsrc/sasl/sysadmin.rst, man/legacy/sasl_server_userdb_setpass_t.3, plugins/cram.c, plugins/digestmd5.c, plugins/kerberos4.c, sample/sample-client.c, sample/sample-server.c, saslauthd/lak.c
These are the findings of the Debian tool lintian.
=> Correct spelling mistakes

include/sasl.h, plugins/gssapi.c
Signed-off-by: Howard Chu <hyc@symas.com>
=> Fix #637 don't enable GSSAPI channel bindings by default

include/saslplug.h, lib/client.c, lib/common.c
Signed-off-by: Howard Chu <hyc@symas.com>
Supersedes #721
=> Fix #386 - honor log_level option on clients too

sasldb/db_gdbm.c
Signed-off-by: Quanah Gibson-Mount <quanah@symas.com>
=> Fix earlier #554 commit to use fetch_errno instead of gdbm_errno

lib/client.c, plugins/anonymous.c
Partially reverts 7ae4341f6226dcb1d4560c665821bc606b8b8ee0
Signed-off-by: Howard Chu <hyc@symas.com>
=> Fix #700 don't fully qualfy client hostname

README.md
Fix #728
Signed-off-by: Howard Chu <hyc@symas.com>
=> Update mailing list info

docsrc/conf.py, docsrc/sasl/authentication_mechanisms.rst, docsrc/sasl/faqs/rfcs.rst
Sources:
- https://github.com/curl/curl/blob/curl-7_84_0/lib/imap.c
- https://tools.ietf.org/doc/tcllib/html/sasl.html
- http://davenport.sourceforge.net/ntlm.html
- some other websites
Ref: #631
=> Write better documentation about all auth mechanisms

plugins/srp.c
The openssl/hmac.h interface is deprecated and might not be available in modern OpenSSL configurations. Replace the HMAC computation in SRP with the equivalent EVP_MAC* calls.
=> srp: Replace HMAC with EVP_MAC implementation

sasldb/db_lmdb.c
=> db_lmdb: fix invalid free in do_open()

m4/sasldb.m4
=> Fix auto_detect for dblib

lib/NTMakefile, plugins/NTMakefile, utils/NTMakefile, win32/common.mak
This doesn't fix all problems because I ran out of steam.
I managed to build successfully by quick&dirty supressing 5 other problems.
2 of which are from https://github.com/cyrusimap/cyrus-sasl/pull/745#issuecomment-1676143030
=> Fix windows build

lib/common.c, saslauthd/auth_krb5.c, saslauthd/testsaslauthd.c
A few possible overruns and a memory leak.
=> Fix some issues uncovered by a static analyzer

sasldb/db_lmdb.c
When the `getopt(cntxt, NULL, "sasldb_path", &p, NULL)` path is taken then SASLDB_FREEPATH is called on a value that can't be free'd and causes a segfault.
=> db_lmdb.c: correctly track if SASLDB_FREEPATH needs to be called

configure.ac
Also fix issues with library checking order.
=> Fixes #839 - Make disable opaque mechanism work
